export const COUNTIES = {
  hcad: {
    id: 'hcad',
    county_name: 'Harris County',
    cad_name: 'HCAD',
    cad_full_name: 'Harris County Appraisal District',
    filing_url: 'owners.hcad.org',
    tax_rate: 0.021,
    arb_address: 'P.O. Box 922012, Houston, TX 77292-2012',
    state: 'Texas',
    db_path: process.env.HCAD_DB_PATH || '/data/hcad.db',
  },
  fbcad: {
    id: 'fbcad',
    county_name: 'Fort Bend County',
    cad_name: 'FBCAD',
    cad_full_name: 'Fort Bend Central Appraisal District',
    filing_url: 'fbcad.org/protests',
    tax_rate: 0.022,
    arb_address: '2801 B.F. Terry Blvd, Rosenberg, TX 77471',
    state: 'Texas',
    db_path: process.env.FBCAD_DB_PATH || '/data/fbcad.db',
  },
  tcad: {
    id: 'tcad',
    county_name: 'Travis County',
    cad_name: 'TCAD',
    cad_full_name: 'Travis Central Appraisal District',
    filing_url: 'traviscad.org/protests',
    tax_rate: 0.019,
    arb_address: '850 E. Anderson Ln, Austin, TX 78752',
    state: 'Texas',
    db_path: process.env.TCAD_DB_PATH || '/data/tcad.db',
  },
};
